spring:
  batch:
    initialize-schema: always
    job:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    schema:
     - classpath:schema.sql
    data:
      - classpath:data.sql
app:
  input-database: mongodb://localhost:27017/library
  output-database: postgresql://localhost:5432/library
