spring:
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
    initialization-mode: always
    schema:
     - classpath:schema.sql
    data:
      - classpath:data.sql
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none