server:
  port: 8082
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  server:
    eviction-interval-timer-in-ms: 15000
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
spring:
  zipkin:
    baseUrl: http://zipkin:9411/
  sleuth:
    enabled: true
  datasource:
    url: jdbc:postgresql://postgres:5432/autoservice
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
management:
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  hystrix:
    enabled: true