version: '3'
services:
  storage:
    build:
      context: ./storage
      dockerfile: Dockerfile
    privileged: true
    ports:
      - "8080:8080"
    container_name: storage-api
    environment:
      - DB_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://postgres:5432/autoservice
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - WAIT_FOR=postgres:5432
  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    container_name: db-storage
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=autoservice
      - DB_DRIVER=org.postgresql.Driver