version: '3'
services:
  postgres:
    image: postgres:12.4
    restart: always
    ports:
      - 5432:5432
    container_name: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "autoservice"
  zipkin:
    image: openzipkin/zipkin:2.21.6
    restart: always
    container_name: zipkin
    ports:
      - 9411:9411