version: '3'
services:
  api:
    build:
      context: ./homework-17-boot
      dockerfile: Dockerfile
    privileged: true
    ports:
      - "8080:8080"
    container_name: api
    environment:
      - DB_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://postgres:5432/library
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - WAIT_FOR=postgres:5432
  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=library
      - DB_DRIVER=org.postgresql.Driver
  library:
    build:
      context: ./homework-angular
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    container_name: library