CREATE TABLE IF NOT EXISTS AUTHORS(ID BIGINT PRIMARY KEY, FULLNAME VARCHAR(255));
CREATE TABLE IF NOT EXISTS GENRES(ID BIGINT PRIMARY KEY, NAME VARCHAR(255));
CREATE TABLE IF NOT EXISTS BOOKS(ID BIGINT PRIMARY KEY, TITLE VARCHAR(255), AUTHOR_ID BIGINT REFERENCES AUTHORS(ID) ON DELETE CASCADE, GENRE_ID BIGINT);